function ologin(){$(".login-hidden").load(root+"/login&ac=mini .login-box-div2",function(){$("#ref-url-l").attr("value",document.location.href)}).fadeIn(700);$(".opc-box").fadeIn()}function removeNotificacao(){$("#nt-1").remove();setTimeout(function(){$("#drop-down-notifications").slideUp("fast")},1100)}function pesquisaNoticia(){var d=$("#pr-search-input").val();window.location=root+"/portal/listn/"+d}
function validaSenha(d){if(d!="")return url=root+"/async/validate",ba=$.ajax({type:"POST",url:url,async:!1,data:{action:"valida_senha",token:1,senha:d},error:function(){showWarn("Ocorreu um erro no processamento.")}}).success(function(d){d=eval("("+d+")");d.response==1?cd=!0:d.response==0&&(cd=!1)}),cd;else{a=document.getElementById("senha").value.length;b=document.getElementById("senha").value;c=document.getElementById("senha-c").value;return a<6?erro="Senha Pequena":b!=c?erro="Confira Senhas":!0}}
function validaTelefone(d){var e;e=d.substring(0,d.length);if(e[0]!="("||e[3]!=")"||e[8]!="-"||d.length<13)return erro="Telefone Inv&aacute;lido.";for(i=0;i<d.length;i++)if(e[i]!=0&&e[i]!=1&&e[i]!=2&&e[i]!=3&&e[i]!=4&&e[i]!=5&&e[i]!=6&&e[i]!=7&&e[i]!=8&&e[i]!=9&&e[i]!=")"&&e[i]!="("&&e[i]!="-")return erro="Telefone Inv&aacute;lido.";return!0}
function validaDia(d){var e=!1;m=document.getElementById("n-mes").value;a=document.getElementById("n-ano").value;if(d.value==null||d.value==0)return!1;if(a%400==0||a%100!=0&&a%4==0)e=!0;return d.value<=31&&(m==1||m==3||m==5||m==7||m==8||m==10||m==12)?!0:d.value<=30&&(m==4||m==6||m==9||m==11)?!0:d.value<=29&&e==!0&&m==2||d.value<=28&&e==!1&&m==2?!0:!1}
function validaParticipantes(){var d=$("#participantes-add").val();if(d.length==0)return!0;d=d.split(";");for(i=0;i<d.length;i++)if(b=validaUsername(d[i]),b!="J&aacute; Cadastrado")return $("#envia-error").html("<span class='side-tip'>Voc\u00ea inseriu participantes que n\u00e3o s\u00e3o v\u00e1lidos.</span>"),!1;$("#envia-error").html("<span class='side-tip-ok'>Participantes v\u00e1lidos.</span>");return!0}
function validaTelefone2(d){var e;e=d.substring(0,d.length);if(d.length==0)return!0;for(i=0;i<d.length;i++)if(e[i]!=0&&e[i]!=1&&e[i]!=2&&e[i]!=3&&e[i]!=4&&e[i]!=5&&e[i]!=6&&e[i]!=7&&e[i]!=8&&e[i]!=9&&e[i]!=")"&&e[i]!="("&&e[i]!="-")return erro="Telefone Inv&aacute;lido.";return!0}
function validaUsername(d){if(/^[a-zA-z1-9][^\\\']+$/.test(d)==!1)return c="Nome Inv\u00e1lido";url=root+"/async/validate";b=$.ajax({type:"POST",url:url,async:!1,data:{login:d,action:"valida_login",token:1},error:function(){showWarn("Ocorreu um erro no processamento.")}}).success(function(d){d=eval("("+d+")");d.response==1?c="J&aacute; Cadastrado":d.response==0&&(c=!0)});d.length<6&&(c="Login Pequeno");return c}
function validaEmail(d,e){emailer=/^[A-Za-z0-9]+([A-Za-z0-9\.-_]*)*@[A-Za-z0-9]+([.]{1}[A-Za-z0-9]+)+$/;emailer.test(d)==!1?c="Email Inv&aacute;lido":(url=root+"/async/validate",a=$.ajax({type:"POST",url:url,async:!1,data:{action:"valida_email",token:1,email:d,id:e},error:function(){showWarn("Ocorreu um erro no processamento.")}}),b=a.success(function(d){d=eval("("+d+")");if(d.response==1)return c="J&aacute; Cadastrado";else if(d.response==0)return c=!0;return"J\u00e1 cadastrado"}));return c}
function trim(d){return d.replace(/^\s+|\s+$/g,"")}function htmlEncode(d){d=d.replace(/&/g,"&amp;");d=d.replace(/'/g,"&#039;");return d=d.replace(/"/g,"&quot;")}
function getPos(){$("#getloc").html("Pegando sua localiza\u00e7\u00e3o...");setTimeout(function(){$("#getloc").html("N\u00e3o foi poss\u00edvel te localizar (Tentar Novamente)!")},1E4);navigator.geolocation.getCurrentPosition(function(d){geocoder=new google.maps.Geocoder;d=new google.maps.LatLng(d.coords.latitude,d.coords.longitude);geocoder&&geocoder.geocode({latLng:d},function(d,f){if(f==google.maps.GeocoderStatus.OK)if(d[0]){var g=d[0].formatted_address,g=g.split(","),h=g[1].split("-"),k=g[2].split("-"),
g=trim(g[0])+" - "+trim(h[0]),h=trim(h[1]),l=trim(k[0]),k=trim(k[1]).toLowerCase();$("#logd").val(g);$("#bairro").val(h);$("#cidade").val(l);$("#"+k).attr("selected","selected");$("#getloc").html("Ok")}else $("#getloc").html("N\u00e3o foi poss\u00edvel te localizar!");else $("#getloc").html("N\u00e3o foi poss\u00edvel te localizar!")})})}
function mapaEvent(d){geocoder=new google.maps.Geocoder;var e={zoom:16,center:new google.maps.LatLng(-34.397,150.644),mapTypeId:google.maps.MapTypeId.ROADMAP};d==1?map=new google.maps.Map(document.getElementById("mapevento"),e):d==2&&(map=new google.maps.Map(document.getElementById("mapevento2"),e))}
function mapaPega(){var d=$("#adress").val();geocoder&&geocoder.geocode({address:d},function(d,f){f==google.maps.GeocoderStatus.OK?(map.setCenter(d[0].geometry.location),new google.maps.Marker({map:map,position:d[0].geometry.location})):showWarn("N\u00e3o foi poss\u00edvel abrir o mapa.")})}function setCookie(d,e,f){var g=new Date;g.setTime(g.getTime()+(f?f*1E3:0));document.cookie=d+"="+escape(e)+(f==null?"":";expires="+g.toGMTString())+";path=/"}
function getCookie(d){if(document.cookie.length>0&&(c_start=document.cookie.indexOf(d+"="),c_start!=-1)){c_start=c_start+d.length+1;c_end=document.cookie.indexOf(";",c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,c_end))}return""}
function desceAbas(){getCookie("_#box-ranking-artista-wrapper")=="hide"&&($("#box-ranking-artista-wrapper").css("display","none"),$("#slide-box-ranking-artista").html("+"));getCookie("_#box-ranking-contratante-wrapper")=="hide"&&($("#box-ranking-contratante-wrapper").css("display","none"),$("#slide-box-ranking-contratante").html("+"));getCookie("_#box-eventos-proximos-wrapper")=="hide"&&($("#box-eventos-proximos-wrapper").css("display","none"),$("#slide-box-eventos-proximos").html("+"));getCookie("_#box-eventos2-recentes-wrapper")==
"hide"&&($("#box-eventos2-recentes-wrapper").css("display","none"),$("#slide-box-eventos2-recentes").html("+"));getCookie("_#box-contatos-recentes-wrapper")=="hide"&&($("#box-contatos-recentes-wrapper").css("display","none"),$("#slide-box-contatos-recentes").html("+"));getCookie("_#box-comentarios-h-wrapper")=="hide"&&($("#box-comentarios-h-wrapper").css("display","none"),$("#slide-box-comentarios-h").html("+"));getCookie("_#box-home-info-wrapper")=="hide"&&($("#box-home-info-wrapper").css("display",
"none"),$("#slide-box-home-info").html("+"));getCookie("_#box-musicas-recentes-wrapper")=="hide"&&($("#box-musicas-recentes-wrapper").css("display","none"),$("#slide-box-musicas-recentes").html("+"));getCookie("_#box-contratos-recentes-wrapper")=="hide"&&($("#box-contratos-recentes-wrapper").css("display","none"),$("#slide-box-contratos-recentes").html("+"))}
function showWarn(d){var e;if(d=="")return!1;clearTimeout(e);$("#error-log").html("<div class='error-warn'>"+d+"</div>");e=setTimeout(function(){$(".error-warn").remove()},3E3);return!0}
function alterarEditTab(){$(document).ready(function(){var d=window.location,d=d.toString(),d=d.split("#");d[1]=="redes"?$(".sub-area-edit").load(root+"/home/edit/&mode=redes .edit-wrapper"):d[1]=="local"?$(".sub-area-edit").load(root+"/home/edit/&mode=local .edit-wrapper"):d[1]=="secu"&&$(".sub-area-edit").load(root+"/home/edit/&mode=secu .edit-wrapper");$("#aba-profile").live("click",function(){location.href="#perfil";$(".sub-area-edit").load(root+"/home/edit/&mode=geral .edit-wrapper");a=["profile",
"redes","local","secu"];for(i=0;i<3;i++)i!=0?$("#aba-"+a[i]).attr("class","menu-abas-edit"):$("#aba-"+a[i]).attr("class","menu-abas-edit2")});$("#aba-redes").bind("click",function(){location.href="#redes";$(".sub-area-edit").load(root+"/home/edit/&mode=redes .edit-wrapper");a=["profile","redes","local","secu"];for(i=0;i<=3;i++)i!=1?$("#aba-"+a[i]).attr("class","menu-abas-edit"):$("#aba-"+a[i]).attr("class","menu-abas-edit2")});$("#aba-local").bind("click",function(){location.href="#local";$(".sub-area-edit").load(root+
"/home/edit/&mode=local .edit-wrapper");a=["profile","redes","local","secu"];for(i=0;i<=3;i++)i!=2?$("#aba-"+a[i]).attr("class","menu-abas-edit"):$("#aba-"+a[i]).attr("class","menu-abas-edit2")});$("#aba-secu").bind("click",function(){location.href="#secu";$(".sub-area-edit").load(root+"/home/edit/&mode=secu .edit-wrapper");a=["profile","redes","local","secu"];for(i=0;i<=3;i++)i!=3?$("#aba-"+a[i]).attr("class","menu-abas-edit"):$("#aba-"+a[i]).attr("class","menu-abas-edit2")})})}
function toolTipClass(){this.toolTipCreator=function(d,e,f,g){document.getElementById(d.id+"-tt")==null&&($("."+e).remove(),$("#"+d.id).bind("mouseleave",function(){(new toolTipClass).toolTipDestroyer(this,90)}),t=setTimeout(function(){var f,k;$("."+e).remove();$("body").after("<div class='"+e+"' id='"+d.id+"-tt' rel='is_tooltip'></div>");f=d;var l=0;k=0;do l+=f.offsetTop||0,k+=f.offsetLeft||0,f=f.offsetParent;while(f);l+=15;k-=45;f=l;$("#"+d.id+"-tt").css("top",f);$("#"+d.id+"-tt").css("left",k);
g()},f))};this.toolTipDestroyer=function(d,e){clearTimeout(t);t=setTimeout(function(){document.getElementById(d.id+"-tt")!=null&&$("#"+d.id+"-tt").fadeOut().remove()},e)}}$("[rel=is_tooltip]").live("mouseleave",function(){clearTimeout(t);$("#"+this.id).remove()});$("[rel=is_tooltip]").live("mouseenter",function(){clearTimeout(t)});
function commentsClass(){var d="",e="";this.getInfo=function(){if($("#user-profile-id").val()!=void 0)e=$("#user-profile-id").val(),d=0;else if($("#event-id").val()!=void 0)e=$("#event-id").val(),d=2;else if($("#music-id").val()!=void 0)e=$("#music-id").val(),d=1;else if($("#contato-id").val()!=void 0)e=$("#contato-id").val(),d=3;else if($("#noticia-id").val()!=void 0)e=$("#noticia-id").val(),d=4;else return d="",!1;return!0};this.showComments=function(f,g){if(this.tipo=="")return!1;var f=parseInt(f),
g=parseInt(g),h;$("#more-comments").html("Carregando...");switch(d){case 0:h="profile";break;case 1:h="music";break;case 2:h="events";break;case 3:h="contato";break;case 4:h="portal"}$.ajax({type:"POST",url:root+"/async/"+h+"/",data:{action:"comment_request",tipo_c:d,id_u:e,page:g,token:1},success:function(d){if($(d).html()!=null){var e=$(d).find("#comment-count").html(),e=parseInt(e),d=$(d).find("#comment-list").html();$("#results-c-m"+f).html(d+"<div id='results-c-m"+(f+1)+"'></div>");$("#comentario-page").attr("value",
f+1);$("#comentario-count").attr("value",g+e);$("#more-comments").html("Coment\u00e1rios carregados.")}else $("#more-comments").html("N\u00e3o foi poss\u00edvel encontrar novos coment\u00e1rios")}});return!0};this.deleteComment=function(d){$("#dc-"+d).html()!="Aguarde..."&&$.ajax({type:"POST",url:root+"/async/main/",data:{action:"delete_comment",id_c:d,token:1},success:function(e){$(e).html()==1?($("#comentario-box-t-"+d).remove(),e=parseInt($("#comentario-count").val()),$("#comentario-count").attr("value",
e-1)):$("body").append("fail")}});$("#dc-"+d).html("Aguarde...")};this.editComment=function(f){e=f.id;var g=f.id.split("-");if($("#"+f.id).html()=="Editar")f=$("#content-ajax-"+g[1]).val(),$("#content-"+g[1]).html("<textarea class='ct-edit"+d+"' id='edit-token-"+g[1]+"'>"+f+"</textarea>"),$("#"+e).html("Ok");else if($("#"+f.id).html()=="Ok"){var h=$("#edit-token-"+g[1]).val();$.ajax({type:"POST",url:root+"/async/main/",data:{action:"edit_comment",id_c:g[1],token:1,text_c:h},success:function(d){d==
""||d==void 0?showWarn("Falha ao editar coment\u00e1rio."):($("#content-ajax-"+g[1]).attr("value",h),$("#content-"+g[1]).html(d),$("#"+e).html("Editar"))}})}};this.addComment=function(f){var g;if(trim(f)=="")return $("#c-error").html("<span class='side-tip'>N\u00e3o \u00e9 poss\u00edvel deixar um coment\u00e1rio em branco.</span>"),!1;if(this.id==""||this.tipo=="")return $("#c-error").html("<span class='side-tip'>Ocorreu um erro durante a insers\u00e3o do coment\u00e1rio.</span>"),!1;switch(d){case 0:g=
"profile";break;case 1:g="music";break;case 2:g="events";break;case 3:g="contato";break;case 4:g="portal"}$("#true-wrap").prepend("<div class='loading-comment'>Criando Coment\u00e1rio</div>");$.ajax({type:"POST",url:root+"/async/"+g+"/",data:{action:"add_comment",id_r:e,token:1,tipo:d,text_c:f},success:function(d){$(".loading-comment").remove();if(d==""||d==void 0)showWarn("Voc\u00ea digitou um coment\u00e1rio inv\u00e1lido.");else{var e=$(d).find("#comment-list").html(),d=$(d).find(".cmt-id").val();
$("#bx-cmt").after(e);e=parseInt($("#comentario-count").val());$("#comentario-count").attr("value",e+1);$("#ultimo-comentario").attr("value",d);$("#c-error").html("")}}});return!0};this.reloadComments=function(){this.getInfo();var f;switch(d){case 0:f="profile";break;case 1:f="music";break;case 2:f="events";break;case 3:f="contato";break;case 4:f="portal"}t=setTimeout(function(){var d=$("#ultimo-comentario").val();$.ajax({type:"POST",url:root+"/async/"+f+"/",data:{action:"reload_comment",max_id:d,
rid:e,token:1},success:function(d){var e=new commentsClass;if(!(d==""||d==void 0)){var f=parseInt($(d).find("#last-id").html()),g=$(d).find("#comment-list").html();$("#bx-cmt").after(g);d=$(d).find("#comment-count").html();d=parseInt(d);g=parseInt($("#comentario-count").val());$("#comentario-count").attr("value",g+d);$("#ultimo-comentario").attr("value",f)}e.reloadComments()}})},9E3)}}
function contatoClass(){this.showDescricao=function(){$("#bci-hide-content").slideUp(300,function(){$("#hide-termos").css("display","none");$("#hide-descricao").is(":hidden")&&$("#hide-descricao").css("display","block");$("#bci-hide-content").slideDown(300);$("#bci-hide-content").css("display","block")})};this.showTermos=function(){$("#bci-hide-content").slideUp(300,function(){$("#hide-descricao").css("display","none");$("#hide-termos").is(":hidden")&&$("#hide-termos").css("display","block");$("#bci-hide-content").slideDown(300);
$("#bci-hide-content").css("display","block")})};this.hideDiv=function(){$("#bci-hide-content").slideUp(300,function(){$("#hide-descricao").css("display","none");$("#hide-termos").css("display","none")});$("#bci-hide-content").css("display","none")};this.startContato=function(d){$(".ajax-box-contato").html("<img src='"+root+"/imagens/site/loading.gif' alt='loading'>");var e=parseInt($("#user-profile-id").val());$.ajax({type:"POST",url:root+"/async/contato/",data:{action:"contato_start",id_r:e,token:1,
step:d},success:function(d){$(".ajax-box-contato").fadeIn();$(".ajax-box-contato").html(d)}})};this.createContato=function(d,e,f,g,h,k){var l=parseInt($("#user-profile-id").val());e.length==1&&(e="01");parseInt(e);$.ajax({type:"POST",url:root+"/async/contato/",data:{action:"contato_start",id_r:l,assunto:d,data:g+"-"+f+"-"+e,valor:h,descricao:k,token:1,step:3},success:function(d){$(".ajax-box-contato").fadeIn();$(".ajax-box-contato").html(d)}})};this.contatoBack=function(d,e,f,g){var h=parseInt($("#user-profile-id").val()),
e=e.split("-");$.ajax({type:"POST",url:root+"/async/contato/",data:{action:"contato_start",id_r:h,assunto:d,data:e,valor:g,descricao:f,token:1,step:2},success:function(d){$(".ajax-box-contato").fadeIn();$(".ajax-box-contato").html(d)}})};this.closeContato=function(d){$(".opc-box").fadeIn();$(".ajax-box-edit").html("<img src='"+root+"/imagens/site/loading.gif' alt='loading'>");$(".ajax-box-edit").fadeIn();var e=parseInt($("#contato-id").val());$.ajax({type:"POST",url:root+"/async/contato/",data:{action:"contato_close",
step:d,id_r:e,token:1},success:function(e){var g=$(e).find("#ajax-response").html(),e=$(e).find("#ajax-content").html();$(".ajax-box-edit").html(e);g==1&&d==1&&($("#status-change").html("<span class = 'color-red'>Fechado</span>"),$("#mci-main").remove(),$("#bci-cancel").remove(),g=parseInt($("#atuantes-count").html())-1,e=parseInt($("#fechados-count").html())+1,$("#atuantes-count").html(g),$("#fechados-count").html(e))}})}}
function curriculumClass(){this.newCurriculum=function(){$.ajax({type:"POST",url:root+"/async/curriculum/",data:{action:"new_curriculum",token:1},success:function(d){d=$(d).html();d==1?$("#cib-true-wrap").load(root+"/contato/curriculum #cib-true-wrap"):showWarn("N\u00e3o foi poss\u00edvel cadastrar seu curriculum.")}})};this.getId=function(){this.id=$("#id-curriculum").val()};this.editCampo=function(d,e){$.ajax({type:"POST",url:root+"/async/curriculum/",data:{action:"edit_campo",campo:d,valor:e,id_c:this.id,
token:1},success:function(f){var g=$(f).find("#response").html(),f=$(f).find("#response-content").html();e==""&&(f="<span class='italic'>Editar</span>");g==1?$("#ce-"+d).html("<span class='c-event-edit' id='cedit-"+d+"'>"+f+"</span>"):showWarn("Erro ao editar campo")}})};this.startEdit=function(d){var e=d.id.split("-"),f,e=e[1],d=$(d).html();if(d=='<span class="italic">Editar</span>'||d=="<SPAN class=italic>Editar</SPAN>")d="";switch(e){case "area":f=20;break;case "instrumento":f=20;break;case "grupo_musical":f=
30;break;case "regiao":f=20}d=htmlEncode(d);e=="sexo"?$("#ce-"+e).html("<select id='"+e+"-edit-cid' class='cid-txt-edit' onkeyup='c= new curriculumClass(); c.keyEnter(this,event.keyCode)'><option value='Masculino'>Masculino</option><option value='Feminino'>Feminino</option><option value='N\u00e3o Informar'>N\u00e3o Informar</option></select>"):$("#ce-"+e).html("<input type='text' id='"+e+"-edit-cid' value='"+d+"' class='cid-txt-edit' maxlength='"+f+"' onkeyup='c= new curriculumClass(); c.keyEnter(this,event.keyCode)'/><span class='enter-info' id='"+
e+'-edit-cid-c\'>Confirme com "Enter"</span>');$("#"+e+"-edit-cid").focus()};this.keyEnter=function(d,e){if(e==13){$("#"+d.id+"-c").css("background","#a00");var f=d.id.split("-"),f=f[0],g=$("#"+d.id).val();c=new curriculumClass;c.getId();c.editCampo(f,g)}};this.deleteCurriculum=function(){$.ajax({type:"POST",url:root+"/async/curriculum/",data:{action:"delete_curriculum",id_c:this.id,token:1},success:function(d){d=$(d).html();d==1?$("#cib-true-wrap").load(root+"/contato/curriculum #cib-true-wrap"):
showWarn("N\u00e3o foi poss\u00edvel deletar o curriculum.")}})};this.addItemLista=function(d,e){var f;switch(d){case 0:f="musicas";d="0";break;case 1:f="contatos";d="1";break;case 2:f="referencias",d="2"}$.ajax({type:"POST",url:root+"/async/curriculum/",data:{action:"additemlista_curriculum",id_c:this.id,tipo:d,item:e,token:1},success:function(e){var h=$(e).find("#response").html(),e=$(e).find("#response-content-ajax").html();h==1?$("#ci-list-"+f).append(e):showWarn("Erro ao inserir item na lista, tente novamente.");
h=new curriculumClass;h.getId();h.reloadInsert(d)}})};this.delItemLista=function(d,e){var f;switch(d){case "0":f="musicas";break;case "1":f="contatos";break;case "2":f="referencias"}$.ajax({type:"POST",url:root+"/async/curriculum/",data:{action:"delitemlista_curriculum",id_c:this.id,tipo:d,pos:e,token:1},success:function(g){g=$(g).html();if(g==1){$("#box-"+f+"-wrap-"+e).remove();var g=document.getElementsByTagName("div"),h;for(h=0;h<g.length;h++){var k=g[h].id,k=k.split("-"),l=k[3];e=parseInt(e);
l=parseInt(l);k=k[1];l>e&&f==k&&(k=l-1,$("#"+g[h].id).attr("id","box-"+f+"-wrap-"+k),$("#cidel-"+d+"-"+l).attr("id","cidel-"+d+"-"+k))}g=new curriculumClass;g.getId();g.reloadInsert(d)}else showWarn("Erro ao deletar item da lista.")}})};this.atualizaCurriculum=function(){$.ajax({type:"POST",url:root+"/async/curriculum/",data:{action:"atualiza_curriculum",id_c:this.id,token:1},success:function(d){d=$(d).html();d==1?$("#cib-true-wrap").load(root+"/contato/curriculum #cib-true-wrap"):showWarn("Erro ao atualizar o curriculum com informa\u00e7\u00f5es de seu perfil.")}})};
this.reloadInsert=function(d){var e;switch(d){case "0":e="musicas";break;case "1":e="contatos";break;case "2":e="referencias"}$.ajax({type:"POST",url:root+"/async/curriculum/",data:{action:"loadinsert_curriculum",id_c:this.id,tipo:d,token:1},success:function(d){$("#ci-insert-"+e).html(d)}})}}
function portalClass(){this.novaNoticia=function(){$("#portal-noticias-wrap").html("<img src='"+root+"/imagens/site/loading.gif' alt='loading'>");$.ajax({type:"POST",url:root+"/async/portal/",data:{action:"new_noticia",token:1},success:function(d){$("#portal-noticias-wrap").html(d)}})};this.deletaNoticia=function(d,e){$(".ajax-box-edit").fadeIn();$(".opc-box").fadeIn();$.ajax({type:"POST",url:root+"/async/portal/",data:{action:"deleta_noticia",step:e,id:d,token:1},success:function(d){var g=$(d).find("#response").html(),
d=$(d).find("#ajax-content").html();e==0?$(".ajax-box-edit").html(d):e==1&&($(".ajax-box-edit").fadeOut(),$(".opc-box").fadeOut(),g==0?showWarn("Falha ao deletar not\u00edcia."):g==1&&$("#portal-full-wrap").html(d))}})};this.boxCreate=function(d){$(".opc-box,.ajax-box-edit").fadeIn();$(".ajax-box-edit").html("<img src='"+root+"/imagens/site/loading.gif' alt='loading'>");switch(d){case 1:$.ajax({type:"POST",url:root+"/async/portal/",data:{action:"create_box",token:1,step:1,id:"",noticia:""},success:function(d){$(".ajax-box-edit").html(d)}})}};
this.editNoticia=function(d,e){if(d==0){var f=$("#noticia-edit-nobb").html();$(".noticia-content").html("<textarea id='edit-noticia2'>"+f+"</textarea><p><input type='button' value='Enviar' id='edit-noticia-btn' class='btn' />")}else if(d==1){var g=$("#edit-noticia2").val();$.ajax({type:"POST",url:root+"/async/portal/",data:{action:"edit_noticia",texto:g,id:e,token:1},success:function(d){var e=$(d).find("#response").html(),d=$(d).find("#ajax-content").html();e==0?(showWarn("Falha ao editar not\u00edcia."),
$(".noticia.content").html(d)):($("#noticia-edit-nobb").html(g),$(".noticia-content").html("<div id='noticia-edit' class='pointer' title='Clique para editar' >"+d+"</div>"))}})}}}
function boxClass(){this.alterarPagina=function(d){var e=parseInt($("#bxl-page").val()),f;switch(d){case 0:f=e+1;$("#bxl-page").attr("value",f);break;case 1:e>0&&(f=e-1,$("#bxl-page").attr("value",f))}$.ajax({type:"POST",url:root+"/async/portal/",data:{action:"bcr_page",page:f,token:1},success:function(d){$(".box-layout-list").html(d)}})};this.selectBox=function(d){if(parseInt($("#bc-selected-box").val())==d)$("#choicebx-"+d).attr("class","box-choice"),$("#noticia-select-bx-wrap").html("<div class='choice-tip'>Selecione a caixa antes de escolher a not\u00edcia.</div>");
else{var e;for(e=1;e<=3;e++)e==d?$("#choicebx-"+e).attr("class","box-choice-selected"):$("#choicebx-"+e).attr("class","box-choice");$("#bc-selected-box").attr("value",d);$("#noticia-select-bx-wrap").html("<img src='"+root+"/imagens/site/loading.gif' alt='loading'>");$.ajax({type:"POST",url:root+"/async/portal/",data:{action:"bcr_loadnoticia",token:1},success:function(d){$("#noticia-select-bx-wrap").html(d)}})}};this.addBox=function(d){var e;d==""?showWarn("Not\u00edcia inv\u00e1lida."):(e=parseInt($("#bc-selected-box").val()),
e<1||e>3?showWarn("Voc\u00ea precisa selecionar uma box."):$.ajax({type:"POST",url:root+"/async/portal/",data:{action:"create_box",tipo:e,noticia:d,step:2,token:1},success:function(d){var e=$(d).find("#response").html(),d=$(d).find("#ajax-content").html();e=="1"?$("#noticia-layout-bx-wrap").html(d):showWarn(d)}}))};this.deleteBox=function(d){$.ajax({type:"POST",url:root+"/async/portal/",data:{action:"delete_box",id:d,token:1},success:function(e){$(e).find("#response").html()=="1"?$("#box-mini-"+d).remove():
showWarn("Falha ao deletar")}})}}
function acompleteClass(){this.abrirAutoComplete=function(d,e,f,g){this.id=e;this.object=d;this.value=f;this.enviarQuery(g)};this.enviarQuery=function(d){var e=this.value,f=this.object,g;$.ajax({type:"POST",url:root+"/async/autocomplete/",data:{action:"auto_complete",id:this.id,valor:e,token:1},success:function(h){var k=$("#"+f.id).val();if(e==k)if(h=eval(h),h==void 0)$("#ac-list-"+f.id).remove();else{var k=f.offsetWidth,l=f.offsetTop+f.offsetHeight,n=f.offsetLeft;$("#ac-list-"+f.id).length==0?($("#"+
f.id).after("<div class='autocomplete-bigidiv' id='ac-list-"+f.id+"' style=\"width: "+k+'px; "></div>'),$("#ac-list-"+f.id).css("top",l),$("#ac-list-"+f.id).css("left",n)):$("#ac-list-"+f.id).html("");$("#"+f.id).bind("blur",function(){clearTimeout(g);g=setTimeout(function(){$("#ac-list-"+f.id).remove()},1100)});$("#ac-list-"+f.id).bind("mouseenter",function(){clearTimeout(g)});$("#ac-list-"+f.id).bind("mouseleave",function(){clearTimeout(g);g=setTimeout(function(){$("#ac-list-"+f.id).remove()},1100)});
var j=0;$.each(h,function(e,g){$(".autocomplete-bigidiv").append("<li valor='"+g.valor+"' class='autocomplete-li' id='ac-list-li-"+f.id+"-"+j+"' >"+g.item+"</li>");$("#ac-list-li-"+f.id+"-"+j).bind("click",function(){var e=$("#"+this.id).attr("valor"),g=$("#"+this.id).html();d!=void 0?d(g,e):$("#"+f.id).attr("value",e);$("#ac-list-"+f.id).remove()});j++})}},error:function(){$("#ac-list-"+f.id).remove()}})}}
function eventoClass(){this.moreEventosVisitados=function(){var d=parseInt($("#mel-page").val());$.ajax({type:"POST",url:root+"/async/events/",data:{action:"update_eventosvisitados",page:d,token:1},success:function(e){e=eval("("+e+")");if(e.response!="1")$(".mel-more").html("Nenhum Evento Encontrado");else{var f=0,g;$.each(e.itens,function(d,e){f++;g="<a href='"+root+"/site/evento/"+e.id+"'> \n                <div class='me-list'> \n                <div class='mel-title'>"+e.nome+"</div> \n                <div class='mel-data'>"+
e.data+"</div> \n                </div></a>";$("#mel-wrap").append(g)});$("#mel-page").attr("value",d+f)}}})};this.deletaEvento=function(d,e){$(".opc-box").fadeIn();$(".ajax-box-edit").html("<img src='"+root+"/imagens/site/loading.gif' alt='Loading' />").fadeIn();$.ajax({type:"POST",url:root+"/async/events/",data:{action:"delete_evento",id:e,step:d,token:1},success:function(f){var g=$(f).find("#response").html(),f=$(f).find("#content").html();g=="1"&&d==1?($(".opc-box,.ajax-box-edit").fadeOut(),$("#evento-info-main-wrap").html(f),
$("#side-list-"+e).remove(),$("#boxev-"+e).remove()):$(".ajax-box-edit").html(f)}})};this.deleteParticipante=function(d,e){$.ajax({type:"POST",url:root+"/async/events/",data:{action:"delete_participante",id_e:d,id_p:e,token:1},success:function(d){$(d).find("#response").html()=="1"?$("#show-participantes-"+e).remove():showWarn("Ocorreu um erro ao deletar o participante.")}})};this.loadEdit=function(d,e){var f;f=e==0?"load_edit":"load_create";$(".opc-box").fadeIn();$(".ajax-box-edit").html("<img src='"+
root+"/imagens/site/loading.gif' alt='Loading' />").fadeIn();$.ajax({type:"POST",url:root+"/async/events/",data:{action:f,id:d,token:1},success:function(d){d=$(d).find("#content").html();$(".ajax-box-edit").html(d)}})};this.editaEvento=function(){var d=$("#e-edit-id").val(),e=$("#nome").val(),f=$("#descricao").val(),g=$("#cidade").val(),h=$("#estado").val(),k=$("#logradouro").val(),l=$("#bairro").val(),n=$("#n-dia").val(),j=document.getElementById("n-dia"),p=$("#n-mes").val(),q=$("#participantes-add").val(),
r=$("#e-minuto").val(),s=$("#e-hora").val(),u=$("#n-ano").val(),o=$("#banner-e-envia").val(),o=o.substr(o.length-4);if(o!=""&&o!=".jpg"&&o!=".png"&&o!=".gif")$("#envia-error").html("<span class='side-tip'>Banner inv\u00e1lido.</span>");else{var o=o.substr(o.length-3),v=$("#genero-e").val();e==""||f==""||g==""||h=="0"||k==""||l==""||n==""?$("#envia-error").html("<span class='side-tip'>Dados necess\u00e1rios n\u00e3o foram preenchidos.</span>"):validaParticipantes()==!1?$("#envia-error").html("<span class='side-tip'>Participantes Inv\u00e1lidos.</span>"):
validaDia(j)==!1?$("#envia-error").html("<span class='side-tip'>Dia Inv\u00e1lido</span>"):($("#envia-error").html("<img src='"+root+"/imagens/site/loading.gif' alt='loading'>"),$.ajax({type:"POST",url:root+"/async/events/",data:{id:d,action:"edit_evento",token:1,param:[e,p,n,s,r,f,k,l,g,h,o,q,v,u]},success:function(e){e=eval("("+e+")");e.response=="1"?($("#envia-error").html("<span class='side-tip-ok'>Edi\u00e7\u00e3o Completa</span>"),$("#evento-info-main-wrap").load(root+"/eventos/"+d+" #evento-info-main-wrap")):
$("#envia-error").html("<span class='side-tip'>"+e.error+"</span>")}}))}};this.editaRede=function(d){var e=d.id.split("-")[0],f;switch(e){case "twitter":f=0;break;case "facebook":f=1;break;case "lastfm":f=2;break;case "youtube":f=3;break;default:return}d=$("#"+d.id).html();if(d=='<span class="italic">editar</span>'||d=="<SPAN class=italic>editar</SPAN>")d="";d=htmlEncode(d);$("#"+e+"-ev-wrap").html("<input type='text' id='"+f+"-rede-txt' class='rd-list-txt' value='"+d+"' />");$("#"+f+"-rede-txt").bind("keyup",
function(d){var e,f,l;if(d.keyCode=="13"){l=this.id;$("#"+this.id).attr("class","rd-list-txt2");e=this.value;d=this.id.split("-")[0];switch(d){case "0":f="twitter";break;case "1":f="facebook";break;case "2":f="lastfm";break;case "3":f="youtube"}d=$("#event-id").val();$.ajax({type:"POST",url:root+"/async/events/",data:{id:d,action:"edit_rede",token:1,rede:f,valor:e},success:function(d){var e=$(d).find("#response").html(),d=$(d).find("#content").html();e=="1"?(d==""&&(d='<span class="italic">editar</span>'),
$("#"+f+"-ev-wrap").html("<div id='"+f+"-ev-insert' class='edita-redes-ev' title='Clique para editar'>"+d+"</div>")):(showWarn("Falha ao inserir campo."),$("#"+l).attr("class","rd-list-txt"))}})}})};this.validaAdicao=function(){$("#e-edit-id").val();var d=$("#nome").val(),e=$("#descricao").val(),f=$("#cidade").val(),g=$("#estado").val(),h=$("#logradouro").val(),k=$("#bairro").val(),l=$("#n-dia").val(),n=document.getElementById("n-dia");$("#n-mes").val();$("#participantes-add").val();$("#e-minuto").val();
$("#e-hora").val();var j=$("#banner-e-envia").val(),j=j.substr(j.length-4);if(j!=""&&j!=".jpg"&&j!=".png"&&j!=".gif")return $("#envia-error").html("<span class='side-tip'>Banner inv\u00e1lido.</span>"),!1;j.substr(j.length-3);$("#genero-e").val();if(d==""||e==""||f==""||g=="0"||h==""||k==""||l=="")return $("#envia-error").html("<span class='side-tip'>Dados necess\u00e1rios n\u00e3o foram preenchidos.</span>"),!1;else if(validaParticipantes()==!1)return $("#envia-error").html("<span class='side-tip'>Participantes Inv\u00e1lidos.</span>"),
!1;else if(validaDia(n)==!1)return $("#envia-error").html("<span class='side-tip'>Dia Inv\u00e1lido</span>"),!1};this.carregaParticipantes=function(d,e,f){$.ajax({type:"POST",url:root+"/async/events/",data:{id:d,action:"carrega_membros",tipo:e,pagina:f,token:1},success:function(){}})}}
function musicaClass(){this.validaForm=function(){var d=$("#titulo").val(),e=$("#genero").val(),f=$("#mp3").val(),d=trim(d),e=trim(e);if(d=="")return $("#form-error").html("<strong class='side-tip'>Nome inv\u00e1lido."),!1;if(e=="")return $("#form-error").html("<strong class='side-tip'>G\u00eanero inv\u00e1lido."),!1;f=f.substr(f.length-3);return f!="mp3"?($("#form-error").html("<strong class='side-tip'>Arquivo mp3 inv\u00e1lido.."),!1):!0};this.showIcons=function(d,e){e=="show"?$("#music-show-info-"+
d+",#music-show-del-"+d).css("display","inline"):$("#music-show-info-"+d+",#music-show-del-"+d).css("display","none")};this.autoLoadMusica=function(){var d;d=window.location;d=d.toString();d=d.split("#");d[1]!=void 0&&d[1]!=""&&this.loadMusica(d[1])};this.loadMusica=function(d){var e=document.getElementById("dir-root").value;$("#me-content").html("Carregando...");$.ajax({type:"POST",url:e+"/async/music/",data:{id:d,action:"carrega_info",token:1},success:function(e){e=$(e).find("#me-content").html();
e==""?$("#me-content").html("M\u00fasica n\u00e3o encontrada."):(location.href="#"+d,$("#me-content").html(e))}})};this.pesquisaMusica=function(d){$("#loading-info").html("<img src='"+root+"/imagens/site/loading.gif' alt='loading'>");var e,f,g;d==!0?(e=$("#ms-nome-input").val(),f=$("#ms-genero-input").val(),g=0):(e=$("#ms-nome").val(),f=$("#ms-genero").val(),g=parseInt($("#ms-page-atual").val()));$.ajax({type:"POST",url:root+"/async/music/",data:{action:"pesquisa_musica",nome:e,genero:f,page:g,token:1},
success:function(h){$("#loading-info").html("");if(h==""||h==void 0)d==!0?($("#ms-response-content").html("<div class='music-search-notfound'>Nenhum resultado encontrado</div>"),$("#more-musicas").remove()):$("#more-musicas").html("Nenhuma m\u00fasica encontrada.");else{$("#more-musicas").html("Mais");h=eval("("+h+")");if(d==!0){if($("#ms-nome-input").val()!=e||$("#ms-genero-input").val()!=f)return;$("#more-musicas").remove();$("#ms-response-content").html("");$("#ms-nome").attr("value",e);$("#ms-genero").attr("value",
f)}$.each(h,function(d,e){var f="<a href='"+root+"/site/musica/"+e.id+"'>\n                  <div class='mser-list-main'><div class='mser-list-nome'>"+e.nome+"</div>\n                  <div class='mser-list-genero'>"+e.genero+"</div>\n                  <div class='mser-list-artista'>"+e.artista+"</div>\n                  <div class='mser-list-duracao'>"+e.duracao+"</div>\n                  </div>\n                  </a>";$("#ms-response-content").append(f)});d==!0&&$("#music-search-content").append("<div id='more-musicas'>Mais</div>");
h=h.length+g;$("#ms-page-atual").attr("value",h)}}})};this.editMusica=function(d,e,f,g,h,k,l){if(d==1){if(trim(f)==""||trim(g)==""){$("#form-error").html("Valores necess\u00e1rios n\u00e3o foram preenchidos.");return}}else $(".opc-box,.ajax-box-edit").fadeIn(),$(".ajax-box-edit").html("<img src='"+root+"/imagens/site/loading.gif' alt='loading'>");$.ajax({type:"POST",url:root+"/async/music/",data:{id:e,step:d,nome:f,genero:g,classificacao:h,privacidade:k,clipe:l,action:"edit_musica",token:1},success:function(f){switch(d){case 0:f=
$(f).find("#form-content").html();$(".ajax-box-edit").html(f);break;case 1:f=eval("("+f+")"),f.response=="1"?($("#form-error").html("Edi\u00e7\u00e3o completada"),(new musicaClass).loadMusica(e)):$("#form-error").html(f.error)}}})};this.deleteMusica=function(d,e){$.ajax({type:"POST",url:root+"/async/music/",data:{id:e,step:d,action:"delete_musica",token:1},success:function(f){if($(f).find("#response").html()=="1")switch(d){case 0:f=$(f).find("#form-content").html();$(".opc-box,.ajax-box-edit").fadeIn();
$(".ajax-box-edit").html(f);break;case 1:$("#nem-bigdiv-"+e).remove(),$("#medit-id").val()==e&&$("#me-content").html("<div class='ms-show-info'>A m\u00fasica que voc\u00ea estava visualizando foi deletada.</div>"),$(".opc-box,.ajax-box-edit").fadeOut()}else showWarn("Falha ao deletar m\u00fasica.")}})};this.editLetra=function(d){switch(d){case 0:d=$("#nobr-letras").html();$(".mec-letras").html("<textarea id='letras-edit'>"+d+"</textarea><input type='button' id='music-btn-letras' value='Alterar' class='btn' >");
break;case 1:var d=$("#letras-edit").val(),e=$("#medit-id").val();$.ajax({type:"POST",url:root+"/async/music/",data:{id:e,letras:d,action:"edit_letras",token:1},success:function(d){d=eval("("+d+")");d.response=="1"?($(".mec-letras").html(d.letra),$("#nobr-letras").html(d.letranobr)):showWarn("Falha ao alterar a letra.")}})}}}
function playlistClass(){var d=document.getElementById("dir-root").value;this.getId=function(){this.id=$("#playlist-id").val()};this.deletePlaylist=function(e){this.getId();var f=this.id;$.ajax({type:"POST",url:d+"/async/playlist/",data:{action:"delete_playlist",id:e,token:1},success:function(d){$(d).find("#response").html()=="1"?($("#playlist-box-"+e).fadeOut(function(){$("#playlist-box-"+e).remove()}),f==e&&$("#playlist-listam-wrapper").html("<div class='playlist-no-playlist'>Nenhuma Playlist Selecionada</div>")):
showWarn("N\u00e3o foi poss\u00edvel deletar a playlist.")}})};this.deleteMusica=function(e){this.getId();$.ajax({type:"POST",url:d+"/async/playlist/",data:{action:"delete_musica",id_p:this.id,id_m:e,token:1},success:function(d){$(d).find("#response").html()=="1"?$("#musica-lista-pl-"+e).fadeOut(function(){$("#musica-lista-pl-"+e).remove()}):showWarn("N\u00e3o foi poss\u00edvel deletar a m\u00fasica.")}})};this.addMusica=function(e,f,g){e!="0"&&$(".amp-left").html("<img src='"+d+"/imagens/site/loading.gif' alt='loading'>");
$(".ajax-box-playlist,.opc-box").fadeIn();$.ajax({type:"POST",url:d+"/async/playlist/",data:{action:"add_musica",step:e,id_p:g,id_m:f,token:1},success:function(d){switch(e){case 0:$(".ajax-box-playlist").html(d);break;case 1:$(".amp-left").html(d);break;case 2:var f=$(d).find("#response").html(),d=$(d).find("#content").html();f=="1"?$(".amp-left").html(d):($(".amp-left").html("<strong>Selecione a playlist</strong>"),showWarn(d))}}})};this.createPlaylist=function(e,f,g){var h="",k;e==1&&(h=$("#pc-nome").val());
$(".ajax-box-playlist,.opc-box").fadeIn();$.ajax({type:"POST",url:d+"/async/playlist/",data:{action:"add_playlist",step:e,id_p:f,id_m:g,nome:h,token:1},success:function(f){switch(e){case 0:$(".ajax-box-playlist").html(f);break;case 1:k=$(f).find("#response").html();f=$(f).find("#pl-id").html();k=="1"?($(".pc-ajax-wrap").animate({"margin-left":"-500"},250),$("#id-play-tobanner").attr("value",parseInt(f))):trim(h)==""?showWarn("Nome invalido"):showWarn("Falha ao criar playlist");break;case 2:var f=
$("#id-play-tobanner").val(),g=$("#music-id").val(),j=$("#pc-imagem").val(),j=j.substr(j.length-4);if(j!=".jpg"&&j!=".png"&&j!=".gif"&&j!="")return showWarn("Imagem inv\u00e1lida."),!1;else g!=null?(j=new playlistClass,j.addMusica(0,g,""),j.addMusica(1,g,f)):($("#lista-playlist-header").load(d+"/playlists/ #lista-playlist-header"),$(".ajax-box-playlist,.opc-box").fadeOut())}}})};this.rollPlaylist=function(d){var f=parseInt($("#lista-playlist-rollwrap").css("margin-left")),g=document.getElementById("lp-b-rp").offsetWidth;
d.id.split("-")[2]=="right"?f*-1+780<g&&$("#lista-playlist-rollwrap").animate({"margin-left":"-=95"},150):(f+=790,f<g&&f<780&&$("#lista-playlist-rollwrap").animate({"margin-left":"+=95"},150))};this.replicaPlaylist=function(e){$(".btn-reply-playlist").remove();$.ajax({type:"POST",url:d+"/async/playlist/",data:{action:"playlist_reply",id_p:e,token:1},success:function(d){var e=$(d).find("#response").html(),h=$(d).find("#error").html();e=="1"?(d=$(d).find("#box").html(),$("#reply-playlist").html("Playlist replicada com sucesso."),
$("#addnpl").after(d)):showWarn(h)}})};this.trocarPrivacidade=function(e,f){$.ajax({type:"POST",url:d+"/async/playlist/",data:{action:"playlist_privacidade",id_p:e,privacidade:f,token:1},success:function(d){d=eval("("+d+")");d.response=="1"?f=="1"?$(".playlist-privacy").html("Playlist Privada (alterar)").attr("id","playlist-privacy-0"):$(".playlist-privacy").html("Playlist P\u00fablica (alterar)").attr("id","playlist-privacy-1"):showWarn("Ocorreu um erro ao alterar a privacidade")}})};this.sortPlaylist=
function(e,f){$.ajax({type:"POST",url:d+"/async/playlist/",data:{action:"sort_playlist",id_p:e,tipo:f,token:1},success:function(d){d=eval("("+d+")");if(d.response!="1")showWarn(d.error);else{var e=[];$.each(d.lista,function(d,f){e[d]=$("#musica-lista-pl-"+f).html();$("#musica-lista-pl-"+f).fadeOut(function(){$("#musica-lista-pl-"+f).remove()})});$.each(e,function(e,f){$("#ul-music-list").append("<li class='music-li-main' id='musica-lista-pl-"+d.lista[e]+"'>"+f+"</li>")})}}})};this.startDrag=function(){$("#opm-list").slideUp();
$("#ul-music-list").disableSelection();$("#true-wrap").append("<div id='end-sortof-playlist'>Arraste os itens da playlist para organizar. (Clique aqui para concluir)</div>");$("#ul-music-list").sortable()};this.endDrag=function(){var e=$("#ul-music-list").sortable("toArray"),f=$("#playlist-id").val();$("#ul-music-list").sortable("destroy");$.ajax({type:"POST",url:d+"/async/playlist/",data:{action:"ddsort_playlist",id_p:f,positions:e,token:1},success:function(d){d=eval("("+d+")");d.response=="1"?$("#end-sortof-playlist").fadeOut(function(){$("#end-sortof-playlist").remove()}):
showWarn("Erro: "+d.error)}})};this.startPlaylist=function(e,f){$("#playlist-listam-wrapper").html("<div class='playlist-no-playlist'>Carregando Playlist...</div>");e=parseInt(e);f=parseInt(f);$.ajax({type:"POST",url:d+"/async/playlist/",data:{action:"start_playlist",id_p:e,id_m:f,token:1},success:function(d){var e=$(d).find("#response").html(),f=$(d).find("#musica").html(),l=$(d).find("#content").html(),d=$(d).find("#barra").html();e!="1"?showWarn("Ocorreu um erro ao carregar a playlist"):($("#true-wrap").append(d),
$("#playlist-body-wrapper").html(l),pt=new playlistClass,pt.loadPlayer(f))}})};this.trocaMusica=function(e){var f;if(e=="")showWarn("Troca de m\u00fasica inv\u00e1lida.");else{f=$("#is-aleatorio").is(":checked")?"1":"0";e=="next"&&(f=="0"?(e=$("#nextm-ipt").val(),e==""&&showWarn("Repetindo playlist.")):e="");if(e=="back"){e=$("#backm-ipt").val();if(e==""){showWarn("N\u00e3o existem m\u00fasicas anteriores.");return}f=="1"&&(e="")}var g=$("#playlist-id").val();$.ajax({type:"POST",url:d+"/async/playlist/",
data:{action:"trocar_musica",id_p:g,id_m:e,aleatorio:f,token:1},success:function(d){var e=$(d).find("#response").html(),f=$(d).find("#musica").html(),g=$(d).find("#letra").html(),j=$(d).find("#proximo").html(),p=$(d).find("#anterior").html(),d=$(d).find("#atual").html();e!="1"?showWarn("Falha ao alterar a m\u00fasica."):($("#playlist-content-letras").html(g),$("#playlist-content-player").fadeOut(function(){pt=new playlistClass;pt.loadPlayer(f);$("#playlist-content-player").fadeIn()}),$(".playlist-content-listamusicas-selected").attr("class",
"playlist-content-listamusicas"),$("#"+f+"-pcl").attr("class","playlist-content-listamusicas-selected"),j=eval("("+j+")"),p=eval("("+p+")"),d=eval("("+d+")"),$("#pmus-nome").html(j.nome),$("#nextm-ipt").attr("value",j.id),$("#amus-nome").html(p.nome),$("#backm-ipt").attr("value",p.id),$(".pbar-mtitle").html(d.nome),$(".ma-genero").html(d.genero),$(".ma-artista").html(d.artista))}})}};this.loadPlayer=function(e){var f;f='<object type="application/x-shockwave-flash" value="transparent" data="'+d+"/swf/music.swf?dir="+
d+"/files/musicas/"+e+'&autoplay=true&playlist=1" width="257" height="130" >';f+="<param name='wmode' value='transparent' />";f+="<param name='movie' value='"+d+"/swf/music.swf?dir="+d+"/files/musicas/"+e+"&autoplay=true&playlist=1' />";f+='<param name="allowScriptAccess" value="always"/>';f+='<embed allowScriptAccess="always" src="'+d+"/swf/music.swf?dir="+d+"/files/musicas/"+e+'&autoplay=true&playlist=1" type="application/x-shockwave-flash"  widt="257" height="130" wmode="transparent" quality=" " />';
f+="</object>";$("#playlist-content-player").html(f)};this.aleatorioOn=function(){$("#is-aleatorio").is(":checked")?$("#amus-nome,#pmus-nome").fadeOut():$("#amus-nome,#pmus-nome").fadeIn()}}
function feedClass(){this.loadFeeds=function(d){var e=document.getElementById("dir-root").value,f=parseInt($("#fi-feed").val()),g=parseInt($("#user-profile-id").val());d==!0?$("#more-full-feed").remove():$("#more-full-atualizacoes").remove();$.ajax({type:"POST",url:e+"/async/feed/",data:{action:"load_feed",id_u:g,first_feed:f,is_feed:d,token:1},success:function(f){var g,f=eval("("+f+")");f.response=="1"?($.each(f.feed,function(d,f){g="<div class='feed-full-list2'>";g+="<div class='ffl-imagem'>";g+=
f.imagem_usuario;g+="</div>";g+="<div class='ffl-content'>";g+="<a href='"+e+"/profile/"+f.login_usuario+"'><div class='ffl-title'>"+f.nome_usuario+"</div></a>";g+=f.escopo_box;g+="</div>";g+="<div class='ffl-date'>"+f.data_formatada+"</div>";g+="<div class='clear'></div>";g+="</div>";$("#feed-list-true-wrap").append(g)}),$("#fi-feed").attr("value",f.first_feed),d==!0?$("#feed-list-true-wrap").after("<div id='more-full-feed'>Carregar mais atualiza\u00e7\u00f5es</div>"):$("#feed-list-true-wrap").after("<div id='more-full-atualizacoes'>Carregar mais atualiza\u00e7\u00f5es</div>")):
d==!0?$("#feed-list-true-wrap").after("<div id='more-full-feed'>N\u00e3o foi poss\u00edvel carregar mais atualiza\u00e7\u00f5es. (Tentar Novamente)</div>"):$("#feed-list-true-wrap").after("<div id='more-full-atualizacoes'>N\u00e3o foi poss\u00edvel carregar mais atualiza\u00e7\u00f5es. (Tentar Novamente)</div>")}})};this.newestFeed=function(){var d=document.getElementById("dir-root").value,e=parseInt($("#user-profile-id").val()),f=parseInt($("#lastf-value").val()),g=parseInt($("#pm-feed").val());
$.ajax({type:"POST",url:d+"/async/feed/",data:{action:"load_newest",id_u:e,last_id:f,token:1},success:function(e){setTimeout(function(){(new feedClass).newestFeed()},16E3);e=eval("("+e+")");if(e.response=="1"){var k=parseInt(e.last_feed),l=parseInt(e.count_feeds),n=parseInt($("#nf-number").val())+l;$("#nf-number").attr("value",n);$("#lastf-value").attr("value",k);$("#pm-feed").attr("value",g+l);k=n==1?"nova atualiza\u00e7\u00e3o.":"novas atualiza\u00e7\u00f5es.";document.getElementById("newest-feed-warning")==
null?($("#nf-number").after("<div id='newest-feed-warning'>"+n+" "+k+"</div>"),$("#newest-feed-warning").bind("click",function(){(new feedClass).showItens()})):$("#newest-feed-warning").html(n+" "+k);$("#newest-feed-content").prepend("<div id='newest-feeds-"+f+"'></div>");var j;$.each(e.feeds,function(e,g){g.nome_usuario!=null&&(j="<div class='feed-full-list2'>",j+="<div class='ffl-imagem'>",j+=g.imagem_usuario,j+="</div>",j+="<div class='ffl-content'>",j+="<a href='"+d+"/profile/"+g.login_usuario+
"'><div class='ffl-title'>"+g.nome_usuario+"</div></a>",j+=g.escopo_box,j+="</div>",j+="<div class='ffl-date'>"+g.data_formatada+"</div>",j+="<div class='clear'></div>",j+="</div>",$("#newest-feeds-"+f).append(j))})}}})};this.showItens=function(){$("#feed-list-true-wrap").prepend($("#newest-feed-content").html());$("#newest-feed-content").html("");$("#nf-number").attr("value",0);$("#newest-feed-warning").unbind("click").remove()};this.acompanhaUser=function(){var d=$("#user-profile-id").val();$.ajax({type:"POST",
url:root+"/async/feed/",data:{action:"acompanhar_user",user_id:d,token:1},success:function(d){d=eval("("+d+")");d.response=="1"?($("#acompanha-btn-1").attr("id","acompanha-btn-2"),$("#acompanha-btn-2").html("Acompanhando")):showWarn(d.error)}})};this.desacompanhaUser=function(){var d=$("#user-profile-id").val();$.ajax({type:"POST",url:root+"/async/feed/",data:{action:"desacompanhar_user",user_id:d,token:1},success:function(d){d=eval("("+d+")");d.response=="1"?($("#acompanha-btn-2").attr("id","acompanha-btn-1"),
$("#acompanha-btn-1").css("background",'url("../imagens/site/acompanha_btn.png") no-repeat'),$("#acompanha-btn-1").html("Acompanhar")):showWarn(d.error)}})}};
